version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      sh -c "pip install --progress-bar off -r requirements.txt && python main.py"
    expose:
      - 8000
    volumes:
      - .:/code
    environment:
      - DEBUG=True
    env_file:
      - .env